-- Buildry Schema (V5 Social Platform)

-- Users table (all account types)
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE,
  name TEXT,
  avatar_url TEXT,
  account_type TEXT CHECK (account_type IN ('developer', 'founder', 'investor', 'recruiter')),
  wallet_address TEXT,
  google_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Builder profiles
CREATE TABLE builder_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  
  -- Identity
  username TEXT UNIQUE NOT NULL,
  bio TEXT,
  tagline TEXT,                    -- "Solana Smart Contract Dev | DeFi Specialist"
  avatar_url TEXT,
  banner_url TEXT,
  location TEXT,
  website TEXT,
  
  -- Socials
  github_username TEXT,
  twitter_handle TEXT,
  telegram_handle TEXT,
  farcaster_handle TEXT,
  linkedin_url TEXT,
  
  -- Wallets
  sol_wallet TEXT,                 -- Solana wallet address
  evm_wallet TEXT,                 -- EVM wallet address
  
  -- Verification flags
  github_verified BOOLEAN DEFAULT FALSE,
  sol_wallet_verified BOOLEAN DEFAULT FALSE,
  evm_wallet_verified BOOLEAN DEFAULT FALSE,
  talent_protocol_verified BOOLEAN DEFAULT FALSE,
  google_verified BOOLEAN DEFAULT TRUE,
  
  -- Talent Protocol
  talent_passport_id TEXT,
  talent_builder_score INTEGER DEFAULT 0,
  talent_data JSONB,               -- full raw response cached
  talent_last_synced TIMESTAMPTZ,
  
  -- Computed scores
  github_score INTEGER DEFAULT 0,
  onchain_sol_score INTEGER DEFAULT 0,  -- from Helius
  onchain_evm_score INTEGER DEFAULT 0,  -- from Alchemy
  overall_score INTEGER DEFAULT 0,      -- weighted composite
  reputation_tier TEXT DEFAULT 'newcomer',
  
  -- GitHub stats (cached from API)
  github_repos INTEGER DEFAULT 0,
  github_commits_90d INTEGER DEFAULT 0,
  github_stars INTEGER DEFAULT 0,
  github_contributions INTEGER DEFAULT 0,
  github_languages JSONB,
  
  -- Onchain stats
  sol_contracts_deployed INTEGER DEFAULT 0,
  sol_transactions INTEGER DEFAULT 0,
  sol_wallet_age_days INTEGER DEFAULT 0,
  evm_contracts_deployed INTEGER DEFAULT 0,
  evm_transactions INTEGER DEFAULT 0,
  evm_wallet_age_days INTEGER DEFAULT 0,
  
  -- Platform stats
  total_jobs_completed INTEGER DEFAULT 0,
  total_earned_usd DECIMAL DEFAULT 0,
  average_rating DECIMAL DEFAULT 0,
  total_reviews INTEGER DEFAULT 0,
  
  -- Skills
  skills TEXT[],                   -- ['Solana', 'Rust', 'React', 'DeFi']
  
  -- Availability
  open_for_work BOOLEAN DEFAULT FALSE,
  hourly_rate_usd INTEGER,
  availability TEXT CHECK (availability IN ('full_time', 'part_time', 'one_off')),
  
  -- AI summary (generated by Claude)
  ai_summary TEXT,
  ai_risk_level TEXT CHECK (ai_risk_level IN ('low', 'medium', 'high')),
  ai_summary_generated_at TIMESTAMPTZ,
  
  is_featured BOOLEAN DEFAULT FALSE,
  profile_complete_pct INTEGER DEFAULT 0,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Projects
CREATE TABLE projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  builder_id UUID REFERENCES builder_profiles(id) ON DELETE CASCADE,
  
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  long_description TEXT,
  banner_url TEXT,
  
  -- Links
  github_url TEXT,
  live_url TEXT,
  demo_url TEXT,
  
  -- Token (Bags)
  has_token BOOLEAN DEFAULT FALSE,
  token_name TEXT,
  token_symbol TEXT,
  token_mint_address TEXT,         -- Solana mint address
  token_launched_at TIMESTAMPTZ,
  token_supply BIGINT,
  reputrade_fee_pct DECIMAL DEFAULT 5.0,
  
  -- Status
  status TEXT CHECK (status IN ('idea', 'building', 'launched', 'completed')) DEFAULT 'building',
  category TEXT,                   -- 'DeFi', 'NFT', 'Infrastructure', 'Tooling', 'Gaming'
  tags TEXT[],
  
  -- Stats
  github_stars INTEGER DEFAULT 0,
  token_holders INTEGER DEFAULT 0,
  token_volume_24h DECIMAL DEFAULT 0,
  token_market_cap DECIMAL DEFAULT 0,
  
  is_featured BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Freelance services
CREATE TABLE services (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  builder_id UUID REFERENCES builder_profiles(id) ON DELETE CASCADE,
  
  title TEXT NOT NULL,             -- "Smart Contract Development"
  description TEXT NOT NULL,
  category TEXT NOT NULL,          -- 'Development', 'Audit', 'Design', 'Consulting'
  
  price_type TEXT CHECK (price_type IN ('fixed', 'hourly', 'negotiable')),
  price_usd INTEGER,               -- in USD
  delivery_days INTEGER,
  
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Jobs / Bounties
CREATE TABLE jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID REFERENCES users(id),
  
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  skills_required TEXT[],
  
  budget_usd INTEGER,
  budget_type TEXT CHECK (budget_type IN ('fixed', 'hourly')),
  deadline TIMESTAMPTZ,
  
  -- Payment
  payment_currency TEXT CHECK (payment_currency IN ('SOL', 'USDC', 'builder_token')),
  
  status TEXT CHECK (status IN ('open', 'in_progress', 'completed', 'cancelled')) DEFAULT 'open',
  
  assigned_builder_id UUID REFERENCES builder_profiles(id),
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Job applications
CREATE TABLE job_applications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id UUID REFERENCES jobs(id),
  builder_id UUID REFERENCES builder_profiles(id),
  cover_letter TEXT,
  proposed_rate INTEGER,
  status TEXT CHECK (status IN ('pending', 'accepted', 'rejected')) DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Escrow contracts
CREATE TABLE escrow_contracts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id UUID REFERENCES jobs(id),
  builder_id UUID REFERENCES builder_profiles(id),
  client_id UUID REFERENCES users(id),
  
  amount_usd DECIMAL NOT NULL,
  payment_token TEXT NOT NULL,     -- 'SOL', 'USDC', or token mint address
  amount_token DECIMAL NOT NULL,
  
  -- On-chain
  escrow_wallet TEXT,              -- escrow smart contract address
  tx_hash TEXT,
  
  reputrade_fee_pct DECIMAL DEFAULT 3.0,
  builder_fee_pct DECIMAL DEFAULT 17.0,   -- distributed to token holders
  
  status TEXT CHECK (status IN ('funded', 'in_progress', 'disputed', 'released', 'refunded')) DEFAULT 'funded',
  
  funded_at TIMESTAMPTZ,
  released_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Reviews (onchain anchored)
CREATE TABLE reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id UUID REFERENCES jobs(id),
  reviewer_id UUID REFERENCES users(id),
  builder_id UUID REFERENCES builder_profiles(id),
  
  rating INTEGER CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  
  onchain_tx TEXT,                 -- tx hash proving review is onchain
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Builder followers / backers
CREATE TABLE builder_followers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  follower_id UUID REFERENCES users(id),
  builder_id UUID REFERENCES builder_profiles(id),
  is_token_holder BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(follower_id, builder_id)
);

-- Notifications
CREATE TABLE notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES users(id),
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  body TEXT,
  link TEXT,
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Social posts (the Instagram-for-startups feed)
CREATE TABLE posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  author_id UUID REFERENCES users(id) ON DELETE CASCADE,

  content TEXT NOT NULL,
  post_type TEXT CHECK (post_type IN ('update', 'milestone', 'launch', 'hiring', 'showcase')) DEFAULT 'update',

  images TEXT[],
  link_url TEXT,
  link_preview JSONB,

  milestone_title TEXT,
  milestone_category TEXT,

  project_id UUID REFERENCES projects(id),

  likes_count INTEGER DEFAULT 0,
  comments_count INTEGER DEFAULT 0,
  reposts_count INTEGER DEFAULT 0,

  is_pinned BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_posts_author ON posts(author_id);
CREATE INDEX idx_posts_created ON posts(created_at DESC);

CREATE TABLE post_likes (
  user_id UUID REFERENCES users(id) ON DELETE CASCADE,
  post_id UUID REFERENCES posts(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, post_id)
);

CREATE TABLE post_comments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID REFERENCES posts(id) ON DELETE CASCADE,
  author_id UUID REFERENCES users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_post_comments_post ON post_comments(post_id);

-- Invest & Trade: Deals (equity, token, SAFE, etc.)
CREATE TABLE deals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  creator_id UUID REFERENCES users(id) ON DELETE CASCADE,
  project_id UUID REFERENCES projects(id),

  title TEXT NOT NULL,
  description TEXT NOT NULL,
  deal_type TEXT CHECK (deal_type IN ('equity', 'token', 'safe', 'convertible', 'revenue_share')) NOT NULL,

  amount_target_usd DECIMAL,
  amount_raised_usd DECIMAL DEFAULT 0,
  min_investment_usd DECIMAL,
  valuation_usd DECIMAL,
  equity_pct DECIMAL,

  token_mint TEXT,
  token_price_usd DECIMAL,

  status TEXT CHECK (status IN ('open', 'funded', 'closed', 'cancelled')) DEFAULT 'open',
  deadline TIMESTAMPTZ,

  tags TEXT[],
  images TEXT[],

  backers_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_deals_status ON deals(status);
CREATE INDEX idx_deals_created ON deals(created_at DESC);

-- Deal investments / backers
CREATE TABLE deal_investments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  deal_id UUID REFERENCES deals(id) ON DELETE CASCADE,
  investor_id UUID REFERENCES users(id) ON DELETE CASCADE,
  amount_usd DECIMAL NOT NULL,
  tx_hash TEXT,
  status TEXT CHECK (status IN ('pending', 'confirmed', 'refunded')) DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Grants & Fellowships
CREATE TABLE grants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  posted_by UUID REFERENCES users(id),

  title TEXT NOT NULL,
  description TEXT NOT NULL,
  organization TEXT NOT NULL,
  grant_type TEXT CHECK (grant_type IN ('grant', 'fellowship', 'accelerator', 'bounty_program')) NOT NULL,

  amount_usd DECIMAL,
  currency TEXT DEFAULT 'USD',
  application_url TEXT,

  deadline TIMESTAMPTZ,
  tags TEXT[],
  ecosystem TEXT,               -- 'Solana', 'Ethereum', 'Base', 'Multi-chain', etc.

  status TEXT CHECK (status IN ('open', 'closed', 'coming_soon')) DEFAULT 'open',

  applicants_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_grants_status ON grants(status);

-- Grant applications
CREATE TABLE grant_applications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  grant_id UUID REFERENCES grants(id) ON DELETE CASCADE,
  applicant_id UUID REFERENCES users(id) ON DELETE CASCADE,
  pitch TEXT,
  status TEXT CHECK (status IN ('submitted', 'reviewing', 'accepted', 'rejected')) DEFAULT 'submitted',
  created_at TIMESTAMPTZ DEFAULT NOW()
);
